### ISSUE TITLE
When test binary is used to run , rerun-fails option does not seem to work

### ISSUE THREAD

**Issue by vedujoshi** [gotestyourself/gotestsum#148]
Am using gotestsum as : 
`~/go/src/gotest.tools/gotestsum/gotestsum  --format standard-verbose --rerun-fails --packages ./... --junitfile ./result.xml --rerun-fails-report something --raw-command -- go tool test2json -t -p global ./global.test -test.run TestPublicObjectUIDGetter -test.v  -test.parallel=1`

When the test fails, the rerun is not happening. Instead i see an error 
`flag provided but not defined: -run`

Per https://github.com/gotestyourself/gotestsum/blob/master/rerunfails.go#L126, Seems like it is set to run only when `go test` is used. 

If i manually change `run` to `test.run` in goTestRunFlagForTestCase() method, it works fine

**Comment by dnephin** [comment]
When `--raw-command` is used, the args are passed as ([src](https://github.com/gotestyourself/gotestsum/blob/13632451686056da4f28577764f100a245857bf8/main.go#L255-L261), [docs](https://github.com/gotestyourself/gotestsum#re-running-failed-tests)):

```
command -run=<test-name> <pkg-name>
```

At the time I thought this would work as-is with a compiled test binary, but I was wrong. I forgot that the test binary expects flags with a `-test.` prefix. So as you noticed it wants `-test.run` instead of `-run`.

I believe it is safe to always use `-test.run` now that I've fixed #122. If you'd like to submit a PR that makes that change you mentioned I would happily accept it! It might require changing some tests.

**Comment by dnephin** [comment]
Thanks you for reporting this problem!  Fixed in #149.
