### ISSUE TITLE
Can't install with `go install` in 1.16 due to use of pflag fork

### ISSUE THREAD

**Issue by mgabeler-lee-6rs** [gotestyourself/gotestsum#176]
The use of a replace directive to use a fork of `pflag` causes issues:
https://github.com/gotestyourself/gotestsum/blob/6d0e3109cfd4f5fcce05a9120f10c5193ab55e42/go.mod#L3

```
$ cd $(mktemp -d)
/tmp/tmp.3upu9q0UQv$ go install gotest.tools/gotestsum@latest
go install gotest.tools/gotestsum@latest: gotest.tools/gotestsum@v1.6.1
        The go.mod file for the module providing named packages contains one or
        more replace directives. It must not contain directives that would cause
        it to be interpreted differently than if it were the main module.
```

I think the replace directive can be removed, however, as github tells me that the fork in question has been fully merged to upstream: https://github.com/spf13/pflag/compare/master...dnephin:master
> spf13:master is up to date with all commits from dnephin:master

**Comment by dnephin** [comment]
Thank you for raising this issue!

The change from my fork is https://github.com/spf13/pflag/pull/259, and it has not yet been merged into upstream. So unfortunately I don't think it is possible to use upstream just yet. Not being able to specify `-test.*` flags is a big problem for a CLI that is `exec` `go test`.

One option would be for me to replace the import path in my fork with `github.com/dnephin/pflag` and use my fork directly instead of as a replace.

I wonder if there is some other way to fix this problem.

**Comment by mgabeler-lee-6rs** [comment]
Oh, I see ... the non-tag version in the replace directive threw me off. Maybe a more acceptable change to upstream pflag would be to be able to opt-out of hiding the test flags? I'll comment over on the linked PR ... again (@fastcat is my personal account, where I've also been doing Go stuff :grin: )

**Comment by mgabeler-lee-6rs** [comment]
Workaround I used in the meantime, in case it helps other visitors to this issue:
`td=$(mktemp -d) && cd $td && go mod init module-install-temp && go get gotest.tools/gotestsum@latest && cd - && rm -rf $td/`
(if adding to a `Makefile` remember to double up the `$`s so it doesn't try to `rm -rf /` :slightly_smiling_face: )

**Comment by dnephin** [comment]
This seems to be working now with the release of v1.6.2
