### ISSUE TITLE
Give option to specify command other than "go test"

### ISSUE THREAD

**Issue by rodrigc** [gotestyourself/gotestsum#18]
Right now, in this code:

https://github.com/gotestyourself/gotestsum/blob/master/main.go#L138

`go test` is invoked under the hood, unless `--raw-command` is specified.

It would be nice to have another option to specify a command other than `go test`.

I have a huge number of tests, and in order to improve syntax checking and performance, I
compile the tests to a binary first:

`go test -c -o mytests`

Then I run:

`mytests`

It would be nice to pass a flag to `gotestsum` which could run the `mytests` binary.

Is it possible to do this now?  I couldn't figure out how to do it.

**Comment by dnephin** [comment]
This is possible, and you are on the right track with `--raw-command`. You'll need to reproduce part of what the `go test -json` command does:

```
go test -c -o mytests
gotestsum --raw-command go tool test2json -p PKGNAME ./mytests -test.v
```

`go tool test2json` and `-test.v` is what converts the test output into json. `PKGNAME` should be the name of the package, I believe it might be just for the test output. Since `mytests` isn't in path it needs to have the relative path `./mytests`.

`go test` also always sets the working directory, so if any tests expect that you'll need to `cd` to the directory as well.

You can debug by using the `--debug` flag which will print the list of command+args that will be executed.

**Comment by rodrigc** [comment]
I verified that `gotestsum --raw-command go tool test2json ./mytests -test.v`
worked for me.  To make things easier for myself, I copied `mytests` to GOPATH.

For now if you could add that as an example in the docs, that would be nice.

Longer term, if you could add a flag to subsume `--raw-command go tool test2json ${SOME_BINARY} -test.v`, that would be nice and a bit easier to use.

**Comment by rodrigc** [comment]
@dnephin With `gotestsum --junitfile report.xml`, is it possible to display output to stdout as the tests are running, instead of waiting for all the tests to complete?
I have some long running tests, and nothing is displayed to stdout until all the tests are over.

**Comment by dnephin** [comment]
The `--junitfile` does not suppress stdout, but it is only written to after the test run is complete.

Which `--format` are you using? The default only prints when the package is done running tests, which might be the problem when the tests are slow. I would try using either `short-verbose`, or `standard-verbose` which uses  the same format as `go test -v`, so you'll get a line printed as test starts and ends.

**Comment by rodrigc** [comment]
I changed my invocation from:


`gotestsum --format standard-verbose --junitfile report.xml`

to:

`gotestsum --format standard-verbose --junitfile report.xml`

and that did the trick of showing output as the test was running, while at the same
time having the `report.xml` file generated and present at the end of the invocation.
