### ISSUE TITLE
Accept `-profile` and `-memprofile` flags and pass them to every package tested

### ISSUE THREAD

**Issue by lukasmalkmus** [gotestyourself/gotestsum#195]
I don't know if this is beyond the scope of this project or how `gotestsum` works internally (so this might not be possible without a lot of modifications) but I still wanted to at least get an opinion on it: What about accepting the `-profile` and `-memprofile` flags and pass them to the `go test` command? Unfortunately, those are only supported on single package tests, e.g. `go test ./pkg/storage/redis` so it is not possible to use them on commands like `gotestsum -- -memprofile=cpuprofile.out ./pkg/storage/...`.

Instead the flag could be part of `gotestsum` and internally it would be passed to every single test.

Thoughts?

**Comment by dnephin** [comment]
Thanks for opening this issue! I think it would be good for `gotestsum` to support running tests with profiling enabled, but I would like to avoid adding flags that already exist on `go test`. I think adding existing `go test` flags sets a precedent that will be hard to maintain. Once `gotestsum` supports a few flags, it will likely have to support more. I think it could also lead to problems where `go test` and `gotestsum` behave in slightly different ways, which would be confusing for users of `gotestsum`.

In a relatively recent version of Go the `go test` command added support for the `-coverprofile` flag with multiple packages, so maybe one day it will also support `-cpuprofile` with multiple packages as well. I suspect that the reason it does not support it today is because using these profile flags leaves the compiled test binary (instead of deleting it), and it requires a different path for the output file in each directory. I think `gotestsum` will face the same problem.

There is one way to run `gotestsum` with these flags today. Using a script and the `--raw-command` flag ([docs](https://github.com/gotestyourself/gotestsum#custom-go-test-command)).

Using a `profile.sh` script like this:

```sh
#!/usr/bin/env bash
set -eu

for pkg in $(go list "$@"); do
    dir="$(go list -f '{{ .Dir }}' $pkg)"
    go test -json -cpuprofile="$dir/cpu.profile" "$pkg"
done
```
You can run:
```
gotestsum --raw-command ./profile.sh ./...
```

The `profile.sh` script passes `"$@"` to `go list`, so you could replace `./...` with any other list of one or more packages and it should still work. Any command line flags that need to be passed to `go test` have to be added to the script, but I imagine that could also be inverted (hard code the list of packages in the script, and pass `"$@"` to `go test` instead, so that other command line flags can be passed to the script), if you preferred that approach.

I think this solution has some nice properties. If you wanted to, you could remove the `pkg.test` file that is left behind, to clean up after the test run. It also gives you full control over the profile filename, and which flags are passed to `go test`, without `gotestsum` needing to know anything about the flags.

The output of running `gotestsum --raw-command ./profile.sh ./...` should be exactly what you would expect from a run without the `--raw-command` flag. It will look like a single run of tests, with a single summary line.

Does this solution seem like it would work for you? This seems like it would be a good addition to the docs, to help others who may be interested in running `go test` with profile flags.

**Comment by lukasmalkmus** [comment]
Thanks for the in-depth explanation! That all sounds completely reasonable. From my side, closing this issue is fine.

Adding the script to the docs sounds like a pretty good idea!
