### ISSUE TITLE
Go test Sum does not pass on environment variables

### ISSUE THREAD

**Issue by dexterp** [gotestyourself/gotestsum#196]
Go test sum does not appear to pass on environment variables to the forked? executions.

This is a ciritcal part of testing and is needed in things such as

1. Skip flags
```go
func TestMyFunction(t *testing.T) {
	if os.Getenv("SKIP_TEST_MYFUNCTION" != "true" {
		t.Skip(`MyFunction test is skipped`)
	}
        # Rest of the code goes here
}
```

2. Feature flags
```go
package fflags

import "os"

// enabled check if feature flags are enabled or disabled
func enabled() bool {
	return os.Getenv("FF_ENABLED") == "true"
}

// MyFeature enables remote operations
func MyFeature() bool {
	return enabled() && os.Getenv("FF_MYFEATURE") == "true"
}
```

**Comment by dnephin** [comment]
Thank you for your interest in `gotestsum`! `gotestsum` most definitely does pass along environment variables. I have used them in test suites before. You can test that it works by running this command:

```
gotestsum --raw-command bash -c '>&2 env'
````

This will run `env` instead of `go test` and prints the output to stderr (so that it is printed by `gotestsum` instead of being handled as `test2json` output). If you run that command you should see it print all the environment variables from the parent shell.

If you provide some more detail about how you are running tests I may be able to help you debug the problem. Sometimes the problem is that environment variables need to be exported using `export`.

**Comment by dexterp** [comment]
I'm looking at my code to see if there is a problem, will get back soon.

**Comment by dexterp** [comment]
I can't reproduce the bug, but I've fiddled with my code for a bit now. Withdrawing bug.
