### ISSUE TITLE
Append to JSON file when --jsonfile is used

### ISSUE THREAD

**Issue by mowies** [gotestyourself/gotestsum#225]
It would be great to have an option to append to a json file with a new flag, e.g. `--append`.

The usecase:
I have several go test files that i can't run all-in-one, so I need to run `gotestsum` multiple times. But in the end I still want one test report with all test results inside.

**Comment by dnephin** [comment]
Thank you for opening this issue! I believe this might be the same issue as #127. Does that sound the same to you?

I suggest a workaround in [the first comment](https://github.com/gotestyourself/gotestsum/issues/127#issuecomment-719967780). By storing the jsonfile for each run you can build a single file by concatenating them all together. Would that work for you here as well?

I am really hesitant to add another flag for this. `gotestsum` already has a large number of flags, and in this case since there is an easy workaround that works for both jsonfile and junitfile.

**Comment by mowies** [comment]
Sounds like a good alternative to me :)
Also, I understand that more flags are not always wanted. Closing this then.
