### ISSUE TITLE
possible bug: build errors passes except when rerun is required

### ISSUE THREAD

**Issue by ashanbrown** [gotestyourself/gotestsum#232]
I have a test that has build errors in it with rerun is enabled, which I think causes it to pass, except when there are test errors.  When there are individual test errors, it reports:

```
ERROR rerun aborted because previous run had errors
```

But otherwise, it passes.

It seems inconsistent to me that the build would pass, except when a test needs a rerun.  This makes it hard to know there is a problem until a test fails.

Just for context, the failures are because I'm trying to run with coverage and `--coverpkg` must include only packages that are included in the build, so we get a few errors like this in the error report: 
```
warning: no packages being tested depend on matches for pattern ...
```

Might we want this test to fail immediately rather than only when a rerun is required?

**Comment by dnephin** [comment]
Thank you for the bug report! I am wondering if this is a case of misleading output. When you say it passes, do you mean the exit code is zero? If you run `echo $?` (to print the exit code of the previous command) it should be non-zero if there were any test failures or build failures.

You may already be familiar with this, but some context to make sure we are on the same page. Any non-zero exit code indicates an error, a 0 exit code indicates success.  Just like `go test` (and most commands on Linux), the canonical way of determining success vs failure is the exit code.  If `gotestsum` is exiting with a code of 0 when some packages fail to build that is definitely a bug, but I have never seen that happen.

If that "warning: no packages being tested depend on matches for pattern" is being sent to stderr,  I think this code https://github.com/gotestyourself/gotestsum/blob/661b09182c5e919dfb1d14994f67578f9797164e/cmd/rerunfails.go#L90-L93 is picking it up as an "error". Sadly build errors only go to stderr, so there's no other way to detect them.

My understanding is this is what might be happening:
* when `--rerun` is not used, we exit here without checking `hasErrors` https://github.com/gotestyourself/gotestsum/blob/661b09182c5e919dfb1d14994f67578f9797164e/cmd/main.go#L218-L219, because `go test` exits with a 0 exit code, so we know no tests have failed.
* when `--rerun` is used, we need to check if it is safe to re-run tests. That's when we go to look at stderr, see those warnings, and prevent the re-run because they could indicate some unexpected failure.

If my understanding is correct, this seems mostly correct to me. If there is a bug, it's that we don't re-run the tests, but erroring on the side of caution in this case seems preferable to accidentally re-running some tests and reporting they all passed when some did not. Maybe the error message could be improved to clarify things.

When `--rerun` is not used, you still see the "warning: no packages being tested" in the output, right? If that is being hidden with some output formats that is a bug I think.

**Comment by ashanbrown** [comment]
Thanks for the detailed reply.  That all sounds consistent with my experience.  As I understand your explanation, the test runner cannot distinguish a test failure from a build failure (which would trigger stderr output) and it doesn't want to rerun on a build failure, so it just refuses to rerun.  The bind that this leaves me in is that the introduction of warnings into my build won't be discovered until a test actually fails.  In other words, I won't immediately know that my build flow is unreliable upon introduction of those warnings; instead, I'll find out later when a test becomes flaky.  Would you be open to a "warnings-are-errors" type option so that we can immediately?  I would argue that this should be the default behavior when reruns are enabled: I'd prefer to find out about changes in build behavior sooner, rather than later.  If there is a case to be made that someone would really prefer to find out later, I'd be interested in hearing it.  Thanks for your consideration.

**Comment by dnephin** [comment]
>  the test runner cannot distinguish a test failure from a build failure

Sorry, I don't think I explained that well. It definitely can distinguish these two things both from the output and from the exit code (build failures will exit with 2, test failures exit with 1).

> The bind that this leaves me in is that the introduction of warnings into my build won't be discovered until a test actually fails. In other words, I won't immediately know that my build flow is unreliable upon introduction of those warnings; instead, I'll find out later when a test becomes flaky

I think I don't fully understand this part. The warnings are the lines that say "warning: no packages being tested depend on matches for pattern", is that right?

It seems like `go test` is only printing those as informational warnings , and doesn't consider those to be failures or errors.  I think that's maybe why you don't see them.  If `go test` considers those to be information then most likely `gotestsum` should as well. If I understand correctly, the bug here is that `gotestsum --rerun-fails` fails to rerun due to these warnings.

Do you not see those warnings in the output of `go test --format testname`? Or is it just that the process exits with 0, so you may not notice?  

If you could provide a full reproduction with all the command line flags you pass to `go test`, I can try to reproduce the issue to understand it better.

I agree with you that if `--rerun-fails` is going to error and refuse to rerun tests because of these warnings, it should do that both when there are tests to rerun and when there is not. There's definitely something to fix here.

**Comment by ashanbrown** [comment]
>  If I understand correctly, the bug here is that gotestsum --rerun-fails fails to rerun due to these warnings.
Yes, that's exactly my concern.  Sorry for not making that clearer.

> Or is it that the process exits with 0, so you may not notice?
Right, I don't notice the warnings.  My builds just keep working like usual.

Here are the details to reproduce:

```
fail.go:
package fail

fail_test.go:
package fail

import "testing"

func TestFail(t *testing.T) {
  t.Fail()
}

> gotestsum --rerun-fails=1 --packages="." -- -cover -coverpkg="github.com/pkg/errors"
warning: no packages being tested depend on matches for pattern github.com/pkg/errors
✖  . (238ms)

=== Failed
=== FAIL: . TestFail (0.00s)

=== Errors
warning: no packages being tested depend on matches for pattern github.com/pkg/errors

DONE 1 tests, 1 failure, 1 error in 0.688s
ERROR rerun aborted because previous run had errors
> echo $status
3
```

**Comment by ashanbrown** [comment]
Hey, I wanted to follow up on this.  I had proposed https://github.com/gotestyourself/gotestsum/pull/235 as a possible fix but that PR was complicated because of how times are captured in test results.  I can try to tackle that if you think the approach is correct.  The gist is that I just suggest we ignore lines beginning with `warning: ` at https://github.com/gotestyourself/gotestsum/pull/235/files#diff-d96005e8f29ffeaf2e143465a9e33d62c226da45755e32a0a227bdd8e6a4f61fR700.  Does that seem reasonable and might you have a suggestion about how to best test this?  Thank you.

**Comment by ashanbrown** [comment]
Thanks for merging my change.  Would it be possible to tag a release?  Thank you.

**Comment by dnephin** [comment]
Done! https://github.com/gotestyourself/gotestsum/releases/tag/v1.8.0
