### ISSUE TITLE
Failure when running tests with coloured log output

### ISSUE THREAD

**Issue by adamcohen2** [gotestyourself/gotestsum#279]
### Summary

`gotestsum` fails when run against tests that produce log output with colour escape sequences.

### Steps to reproduce

1. Create a test, for example, called `testing_test.go`, that uses a custom log message with a colour escape sequence:

   ```go
   package testing
   
   import (
     "fmt"
     "testing"
   
     log "github.com/sirupsen/logrus"
   )
   
   // Formatter is used to by the logrus package to provide a custom logger
   type Formatter struct{}
   
   // Format creates a custom log formatter so we can colorize and format the output
   func (f *Formatter) Format(entry *log.Entry) ([]byte, error) {
     colorWarn := "\x1b[0;33m%s\x1b[0m"
   
     logEntry := fmt.Sprintf("%s\n", entry.Message)
     logEntry = fmt.Sprintf(colorWarn, logEntry)
   
     return []byte(logEntry), nil
   }
   
   func Test(t *testing.T) {
     log.SetFormatter(&Formatter{})
     log.Info("Info Message")
   }
   ```

1. Run `gotestsum`, a failure is reported:

   ```shell
   $ gotestsum ./...
   
   ✓  . (267ms)
   
   === Failed
   === FAIL: . Test (unknown)
   Info Message
   --- PASS: Test (0.00s)
   
   DONE 1 tests, 1 failure in 0.888s
   ```

1. If we disable log output, `gotestsum` passes as expected:

   1. Add the following to `testing_test.go`:

      ```go
      func init() {
        // Suppress noisy warnings during test execution
        logrus.SetOutput(ioutil.Discard)
      }
      ```

   1. Run `gotestsum`, it passes as expected:

      ```shell
      $ gotestsum ./...
   
      ✓  . (260ms)
      
      DONE 1 tests in 1.086s
      ```

### What is the current *bug* behavior?

`gotestsum` reports a failure

### What is the expected *correct* behavior?

`gotestsum` should succeed

**Comment by dnephin** [comment]
That you for the bug report!

I believe this might be a bug in the formatter related to https://github.com/golang/go/issues/26325.

If I am reading the code you shared correctly, the log message will be output like this:

```
\x1b[0;33mMSG
\x1b[0m
```

The newline is before the color reset characters. This causes the framing events used by `go test -json` to not start at the beginning of a line. See this comment: https://github.com/golang/go/issues/26325#issuecomment-404232647 and the [following proposed solution](https://github.com/golang/go/issues/26325#issuecomment-880034679).
`gotestsum` uses the output of `go test -json`, and since it's not able to find the "test passed" event, it has to display the "unknown" failure. I believe the exit code of the process is correctly 0 (`echo $?`).

I think if you change the formatter to output this the problem should go away:

```
\x1b[0;33mMSG\x1b[0m
```

**Comment by adamcohen2** [comment]
> The newline is before the color reset characters. This is effectively the same thing as outputting a line with a missing trailing newline. This causes the framing events used by `go test -json` to not start at the beginning of a line

Thanks for the quick response @dnephin! You're correct about the malformed log message - it wasn't affecting us until we ran into an issue with `gotestsum`, but it looks like this is easily fixable on our side and not a bug with `gotestsum`. Thanks again for your help, I'm going to close this bug report.
