### ISSUE TITLE
Add support for build tags in gotestsum

### ISSUE THREAD

**Issue by dejanzele** [gotestyourself/gotestsum#308]
# Problem

Currently, the go test tool supports adding build tags with the `--tags` flag, which is useful for conditional compilation and testing. However, the gotestsum tool does not currently support build tags.

It would be great if gotestsum could support build tags, as this would make it easier to run tests with different build configurations, especially in larger projects with many tests and different build configurations.

Could we add support for build tags in gotestsum? This would be a very helpful feature for many developers.

# Proposed Solution

Add a `-t|--tags` flag where user can provide a comma-separated list of build tags. 

I'd also be interested in helping out and implementing this feature if possible.

**Comment by dnephin** [comment]
I'm guessing you found the solution to this problem. Just in case someone else finds this issue, I'll post it here as well.

You can pass any `go test` flags along by including them after a `--`:

```
$ gotestsum --format testname -- --tags=foo ./...
```

Be sure to include the list of packages if you use any `go test` flags, because the default of `./...` will not be applied once you add any flags after `--`.
