### ISSUE TITLE
Add support Ginkgo testing framework

### ISSUE THREAD

**Issue by BorzdeG** [gotestyourself/gotestsum#320]
https://github.com/onsi/ginkgo

**Comment by dnephin** [comment]
Thank you for your interest in gotestsum! I think this issue is a duplicate of #273, so I'm going to close it. Let's continue the discussion in that issue.

I've never used ginkgo myself, but generally I would recommend people try to write tests without it. The standard `testing` package makes it pretty easy to write tests in this style without the extra dependency.

For example: https://github.com/golang/go/issues/59291#issuecomment-1499328326
