### ISSUE TITLE
Coverage not reported

### ISSUE THREAD

**Issue by dahu33** [gotestyourself/gotestsum#322]
When I run `gotestsum -- -cover ./...` I don't have any coverage reported anywhere. Is that expected? 

My golang version is 1.20.3.

**Comment by dnephin** [comment]
Thank you for the bug report! It looks like the `go test -json` output has changed. Instead of a separate line of output with  
````
coverage: n% of statements
````

Now the coverage line seems to be appended to other lines, the "ok" line, and the elapsed time of the package.

I believe go1.20 made some changes to the test output, this may have been a side-effect. I don't see an Go issue about this yet. I imagine it's not a high priority for them to keep this output stable.

It shouldn't be too difficult to fix this in `gotestsum`.
