### ISSUE TITLE
Ability to apply a transformation to the "testsuite" name in junit

### ISSUE THREAD

**Issue by ijc** [gotestyourself/gotestsum#50]
If I run tests on a package `github.com/ijc/foo/...` using `-junitfile` then I get results with:
```
<testsuite tests="33" failures="0" time="0.000000" name="github.com/ijc/foo/bar">
...
<testsuite tests="33" failures="0" time="0.000000" name="github.com/ijc/foo/baz">
```
...so far so good.

However if I feed this into Jenkins it creates me a directory named "github" and within that there are two entries "com/ijc/foo/bar" and "com/ijc/foo/baz", this is not really a desirable presentation.

It would be useful if gotestsum could allow fiddling with the name somehow. My preference would be to allow specifying a (common) prefix to be dropped from all the suite names (e.g. I would likely choose to drop `github.com/ijc/foo/`). A variant of that would be a `-p«N»` option (cf `patch(1)`) to strip «n» path elements.

I'm not sure if other transformations might be useful/better e.g. `tr . -` or some sort of escaping. 

Just stripping a prefix has the benefit of being nice and simple I think.

**Comment by dnephin** [comment]
Do you have a link to the jenkins plugin that does this? I wonder what logic it uses to make the directory structure. I guess Java class paths are separated by dots, which is why it has done this? If that is the case another option might be to convert the path into something that resembles a valid java path (ex: `githubcom.ijc.foo`

This change (#49) was made recently ([v0.3.4](https://github.com/gotestyourself/gotestsum/releases/tag/v0.3.4)) to improve integration with CircleCI. I wonder if that will cause any problems with the jenkins plugin.

Generally making the junit report integrate better with CI systems makes sense to me.

**Comment by ijc** [comment]
Yes, I suspect this is something to do with Java class path separators.

I'm using a hosted Jenkins so the `junit` plugin was there already, I believe it is the standard one though which is https://wiki.jenkins.io/display/JENKINS/JUnit+Plugin.

Switching to `githubcom.ijc.foo` I think would work, although it would mean a three level deep thing in Jenkins I suspect (`githubcom`→`ijc`→`foo`, then plus the subpackages in my project), but I think that's then "working as Jenkins designed" and it is at least better than `github`→`com/ijc/foo`. I would still prefer the prefix strip option but could live with your proposal.

**Comment by ijc** [comment]
I found a (very gross) workaround:

```
gotestsum --raw-command -- sh -c 'go list ./... | sed -e "s,^github.com/ijc/foo/\?,/,g" | xargs -I{} -n1 go tool test2json -p unit{} -t go test -v github.com/ijc/foo{}'
```
(the `/\?` thing in the `sed` is to turn the line matching `^github.com/ijc/foo$` into `/` and not the empty string so that `xargs` will actual emit something, so we end up with `-p unit/` or `-p unit/subpackage` etc)
