### ISSUE TITLE
Bitbucket Pipelines Test reporting displaying tests incorrectly

### ISSUE THREAD

**Issue by Trane9991** [gotestyourself/gotestsum#68]
I'm using this with the [Bitbucket Pipelines Test reporting](https://confluence.atlassian.com/bitbucket/test-reporting-in-pipelines-939708543.html) and found an issue that test results displayed incorrectly.

Following input:
```xml
    <testsuite tests="14" failures="2" time="1.161" name="github.com/my_org/path/to/pkg">
        <properties>
            <property name="go.version" value="go1.13"></property>
        </properties>
        <testcase classname="github.com/my_org/path/to/pkg" name="TestInMyPkg" time="0.000">
            <failure message="Failed" type="">Example Error Message</failure>
        </testcase>
    </testsuite>
```

results in following test representation in Bitbucket Pipelines:
<img width="674" alt="Screen Shot 2019-09-25 at 4 28 38 PM" src="https://user-images.githubusercontent.com/9948629/65605402-b62b3080-dfb1-11e9-83da-dfe45924d187.png">

While input with the short package name in the `classname` property:
```xml
    <testsuite tests="14" failures="2" time="1.161" name="github.com/my_org/path/to/pkg">
        <properties>
            <property name="go.version" value="go1.13"></property>
        </properties>
        <testcase classname="pkg" name="TestInMyPkg" time="0.000">
            <failure message="Failed" type="">Example Error Message</failure>
        </testcase>
    </testsuite>
```

Results in the much better representation on the Bitbucket Pipeliens UI:
<img width="674" alt="Screen Shot 2019-09-25 at 4 31 09 PM" src="https://user-images.githubusercontent.com/9948629/65605531-ec68b000-dfb1-11e9-87de-e437e4d334a0.png">

**Comment by Trane9991** [comment]
I think it should be fine changing it to use the short package name in the `testcase.classname` the property, since long package name already present in the `testsuite.name`.

**Comment by dnephin** [comment]
Hi, Thank you for opening this issue!

Making changes to the junit.xml is challenging, because it seems that every CI system uses it in a slightly different way.For example see issue #50, which is still open as well.

I think the proposed change in #68 would make the output worse on other CI systems.

I'd like to find some way that allows everyone to customize the fields as necessary for their CI system, but I'm not exactly sure what that would look like yet.

**Comment by dnephin** [comment]
#49 also seems relevant, which effectively is the opposite change to this PR. It sounds like the bug here might be in Bitbucket Pipelines Test reporting, it seems to be doing something different from all the other tools.

That said, I am still interested in finding a way to make it work for all tools, by allowing fields to be customized.

**Comment by Trane9991** [comment]
hmm... maybe some additional flag something like `--short-package-name` to cover both cases?

**Comment by dnephin** [comment]
I've added some flags in #70 which should hopefully work for both cases

**Comment by Trane9991** [comment]
Thanks, looks cool!
