### ISSUE TITLE
how to use this in e2e tests binaries?

### ISSUE THREAD

**Issue by medyagh** [gotestyourself/gotestsum#77]
I am interested to add this to minikube e2e tests, but I am not sure how I would use it, we build e2e binaries for the the tests and run it on different platforms. could I still use this tool?

**Comment by dnephin** [comment]
Yes, absolutely! There are some examples which are close to that usage here: https://github.com/gotestyourself/gotestsum#custom-go-test-command

The `-json` flag is handled by `go test` itself, it is not available when using a compiled test binary, so you'll need to call `go tool test2json` to get the output that `gotestsum` expects.

Something like this has worked for me:

```
gotestsum --raw-command -- go tool test2json -p pkgname ./binary.test -test.v
```

`pkgname` is the name of the package, used to report output. Normally `go test` passes that value, so we have to pass it in.
`./binary.test` is the path to the compiled binary, and `-test.v` is required so that all the output is available to `test2json`.

I hope that helps! Let me know if you run into problems and I might be able to help get it working.

This would probably be an excellent example to add to the README as well.
