### ISSUE TITLE
support other pipe-friendly reporters

### ISSUE THREAD

**Issue by amir-arad** [gotestyourself/gotestsum#78]
[tparse](https://github.com/mfridman/tparse) can be chained elegantly and effortlessly, while keeping junit xml output functionality for CI

**Comment by dnephin** [comment]
Sorry, I don't understand this feature request. What are you interested in seeing added?

Are you saying you would like to do something like this?

```
gotestsum --junitxmlfile junit.xml | tparse
```

That could be accomplished by adding a `--json` format which prints out the `test2json` unformatted.

Although it seems strange that you would need to use `tparse` at all. `gotestsum` should be able to output a similar format to `tparse`, something like `--format table`.

Is this what you are asking for?

**Comment by dnephin** [comment]
Receiving output from `go test -json` via pipe is not sufficient. Build errors are  reported on stderr. It is necessary to run the process so that both stdout and stderr can be captured, to properly report on build errors.

Looking at `tparse`, it seems like piping output to it is unnecessary. It doesn't actually print output while the tests are running, it waits until all the output is captured. I guess this is necessary so that the table can be formatted correctly. So you gain nothing by sending it output as a stream. Doing the following would be equivalent to a pipe:

```
gotestsum --jsonfile json.out --junitxmlfile junit.xml
cat json.out | tparse
```

So I think you can probably accomplish what you want already. What do you think?

**Comment by amir-arad** [comment]
That's a good solution. thanks.

My original idea was something like 
```
gotestsum --junitxmlfile junit.xml --format-external "tparse -all"
```
or
```
gotestsum --jsonfile /dev/stdout --junitxmlfile junit.xml  --silent | tparse -all
```
assuming tparse is already installed in the machine
